version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo_volume:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev  # Để chuyển sang production, thay đổi thành 'prod'
    volumes:
      - .:/app  # Mount code vào container để live reload
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
volumes:
  mongo_volume:
